 #
# Do not hand edit this file. It was generated by
# /mu2e/app/users/sophie/BTrk/BTrk/BTrk/newBuild.sh
#

if [ "" = "setup.sh" ];then
    echo "You should be sourcing this file, not executing it."
    exit 1
fi
export PACKAGE_SOURCE=/mu2e/app/users/sophie/BTrk/BTrk/BTrk
export DEBUG_LEVEL=prof
source ${PACKAGE_SOURCE}/setup.sh
